# Generated by Django 4.0.3 on 2022-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='last_bid',
            field=models.IntegerField(default=0),
        ),
    ]
